# Generated by Django 5.2.8 on 2025-11-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frigorifico_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bovino',
            name='numero_brinco',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número do Brinco'),
        ),
    ]