# Generated by Django 5.2.8 on 2025-11-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frigorifico_app', '0002_alter_bovino_numero_brinco'),
    ]

    operations = [
        migrations.AddField(
            model_name='bovino',
            name='status_avaliacao',
            field=models.CharField(choices=[('nao_avaliado', 'Não Avaliado'), ('apto', 'Apto para Comercialização'), ('inapto', 'Inapto para Comercialização')], default='nao_avaliado', max_length=20, verbose_name='Status da Avaliação'),
        ),
        migrations.AddField(
            model_name='bovino',
            name='observacoes_avaliacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observações da Avaliação'),
        ),
        migrations.AddField(
            model_name='bovino',
            name='data_avaliacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Avaliação'),
        ),
    ]