# Generated by Django 5.2.8 on 2025-11-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frigorifico_app', '0004_bovino_detailed_evaluation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='bovino',
            name='tipo_animal',
            field=models.CharField(blank=True, choices=[('vaca', 'Vaca'), ('boi', 'Boi'), ('touro', 'Touro'), ('novilha', 'Novilha')], max_length=20, null=True, verbose_name='Tipo do Animal'),
        ),
        migrations.AddField(
            model_name='bovino',
            name='qualidade',
            field=models.CharField(blank=True, choices=[('desossa', 'Desossa'), ('fraca', 'Fraca'), ('media', 'Média'), ('boa', 'Boa'), ('condenada', 'Condenada')], max_length=20, null=True, verbose_name='Qualidade'),
        ),
        migrations.AddField(
            model_name='bovino',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AddField(
            model_name='bovino',
            name='data_classificacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Classificação'),
        ),
    ]