# Generated by Django 5.2.8 on 2025-11-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frigorifico_app', '0005_bovino_classification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='bovino',
            name='posicao_trilho',
            field=models.IntegerField(blank=True, null=True, verbose_name='Posição do Trilho'),
        ),
        migrations.AddField(
            model_name='bovino',
            name='posicao_gancho',
            field=models.IntegerField(blank=True, null=True, verbose_name='Posição do Gancho'),
        ),
        migrations.AddField(
            model_name='bovino',
            name='data_entrada_estoque',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Entrada no Estoque'),
        ),
    ]