# Generated by Django 5.2.8 on 2025-11-08 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frigorifico_app', '0006_bovino_storage_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeiaCarcaça',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lado', models.CharField(choices=[('esquerda', 'Esquerda'), ('direita', 'Direita')], max_length=10, verbose_name='Lado da Carcaça')),
                ('posicao_trilho', models.IntegerField(blank=True, null=True, verbose_name='Posição do Trilho')),
                ('posicao_gancho', models.IntegerField(blank=True, null=True, verbose_name='Posição do Gancho')),
                ('data_entrada_estoque', models.DateTimeField(blank=True, null=True, verbose_name='Data de Entrada no Estoque')),
                ('bovino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frigorifico_app.bovino', verbose_name='Bovino')),
            ],
            options={
                'verbose_name': 'Meia Carcaça',
                'verbose_name_plural': 'Meias Carcaças',
            },
        ),
    ]