# Generated by Django 5.2.8 on 2025-11-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frigorifico_app', '0007_meiacarcaça'),
    ]

    operations = [
        migrations.AddField(
            model_name='meiacarcaça',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Peso (kg)'),
        ),
    ]