# Generated by Django 5.2.8 on 2025-12-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frigorifico_app', '0012_meiacarcaça_comprador_meiacarcaça_data_venda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meiacarcaça',
            name='data_entrada_estoque',
            field=models.DateTimeField(),
        ),
    ]
