# Generated by Django 5.2.8 on 2026-03-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frigorifico_app', '0013_alter_meiacarcaça_data_entrada_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='meiacarcaça',
            name='data_saida_estoque',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
