# Generated by Django 5.2.8 on 2026-03-14 12:29

from django.db import migrations, models


def preencher_avaliacao_nulos(apps, schema_editor):
    Bovino = apps.get_model('frigorifico_app', 'Bovino')
    campos = [
        'condicao_geral', 'carcassa', 'figado', 'coracao', 'pulmoes', 'rins',
        'diafragma', 'lingua', 'cabeca', 'utero', 'baco_pancreas',
        'intestino_estomagos_bexiga', 'glandula_mamaria'
    ]
    for c in campos:
        Bovino.objects.filter(**{f'{c}__isnull': True}).update(**{c: 'Aprovado'})


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('frigorifico_app', '0014_meiacarcaca_data_saida_estoque'),
    ]

    operations = [
        migrations.RunPython(preencher_avaliacao_nulos, reverse_noop),
        migrations.AlterField(
            model_name='bovino',
            name='baco_pancreas',
            field=models.CharField(choices=[('Aprovado', 'Aprovado'), ('Abscesso', 'Abscesso'), ('Aspecto repugnante', 'Aspecto repugnante'), ('Esplenomegalia', 'Esplenomegalia'), ('Euritrema', 'Euritrema'), ('Aderencia', 'Aderencia')], default='Aprovado', max_length=50),
        ),
        migrations.AlterField(
            model_name='bovino',
            name='cabeca',
            field=models.CharField(choices=[('Aprovado', 'Aprovado'), ('Cont. Gastro/Biliar', 'Cont. Gastro/Biliar'), ('Cisticercose Calcificada', 'Cisticercose Calcificada'), ('Cisticercose Viva', 'Cisticercose Viva')], default='Aprovado', max_length=50),
        ),
        migrations.AlterField(
            model_name='bovino',
            name='carcassa',
            field=models.CharField(choices=[('Aprovado', 'Aprovado'), ('Abscessos', 'Abscessos'), ('Cisticercose Viva', 'Cisticercose Viva'), ('Cisticercose Calcificada', 'Cisticercose Calcificada'), ('Hemorragias', 'Hemorragias'), ('Cont. Gastro/biliar', 'Cont. Gastro/biliar'), ('Aderencia', 'Aderencia'), ('Artrite', 'Artrite'), ('Aspecto repugnante', 'Aspecto repugnante'), ('Neoplasia', 'Neoplasia'), ('Magreza', 'Magreza'), ('Evisceração Retardada', 'Evisceração Retardada'), ('Peritonite', 'Peritonite'), ('Caquexia', 'Caquexia'), ('Sarcosporidiose', 'Sarcosporidiose'), ('Contusão/Fratura', 'Contusão/Fratura'), ('Icterícia', 'Icterícia'), ('Adenite', 'Adenite')], default='Aprovado', max_length=50, verbose_name='Carcaça'),
        ),
        migrations.AlterField(
            model_name='bovino',
            name='condicao_geral',
            field=models.CharField(choices=[('Aprovado', 'Aprovado'), ('Condenação Total', 'Condenação Total'), ('Em Inspeção', 'Em Inspeção'), ('Condenação Parcial', 'Condenação Parcial')], default='Aprovado', max_length=50),
        ),
        migrations.AlterField(
            model_name='bovino',
            name='coracao',
            field=models.CharField(choices=[('Aprovado', 'Aprovado'), ('Cisticercose Calcificada', 'Cisticercose Calcificada'), ('Cisticercose Viva', 'Cisticercose Viva'), ('Pericardite', 'Pericardite'), ('Endocardite', 'Endocardite'), ('Hidatidose', 'Hidatidose'), ('Melanose', 'Melanose'), ('Sarcosporidiose', 'Sarcosporidiose')], default='Aprovado', max_length=50),
        ),
        migrations.AlterField(
            model_name='bovino',
            name='diafragma',
            field=models.CharField(choices=[('Aprovado', 'Aprovado'), ('Aderência', 'Aderência'), ('Cisticercose Viva', 'Cisticercose Viva'), ('Cisticercose Calcificada', 'Cisticercose Calcificada'), ('Perihepatite', 'Perihepatite'), ('Icterícia', 'Icterícia'), ('Sarcosporidiose', 'Sarcosporidiose')], default='Aprovado', max_length=50),
        ),
        migrations.AlterField(
            model_name='bovino',
            name='figado',
            field=models.CharField(choices=[('Aprovado', 'Aprovado'), ('Abcessos Múltiplos', 'Abcessos Múltiplos'), ('Cirrose', 'Cirrose'), ('Congestão/Teleangiectasia', 'Congestão/Teleangiectasia'), ('Faciolose', 'Faciolose'), ('Contaminação Biliar', 'Contaminação Biliar'), ('Perihepatite', 'Perihepatite'), ('Cisticercose Viva', 'Cisticercose Viva'), ('Cisticercose Calcificada', 'Cisticercose Calcificada'), ('Hidatidose', 'Hidatidose')], default='Aprovado', max_length=50),
        ),
        migrations.AlterField(
            model_name='bovino',
            name='glandula_mamaria',
            field=models.CharField(choices=[('Aprovado', 'Aprovado'), ('Adenite', 'Adenite'), ('Mastite', 'Mastite'), ('Miiase', 'Miiase'), ('Aspecto repugnante', 'Aspecto repugnante')], default='Aprovado', max_length=50),
        ),
        migrations.AlterField(
            model_name='bovino',
            name='intestino_estomagos_bexiga',
            field=models.CharField(choices=[('Aprovado', 'Aprovado'), ('Abscessos', 'Abscessos'), ('Enterite', 'Enterite'), ('Peritonite', 'Peritonite'), ('Tuberculose(Lesão Sugestiva)', 'Tuberculose(Lesão Sugestiva)'), ('Linfadenite', 'Linfadenite'), ('Adenite', 'Adenite'), ('Parasitoses', 'Parasitoses'), ('Esofagostomose', 'Esofagostomose'), ('Neoplasia', 'Neoplasia')], default='Aprovado', max_length=50),
        ),
        migrations.AlterField(
            model_name='bovino',
            name='lingua',
            field=models.CharField(choices=[('Aprovado', 'Aprovado'), ('Cont. Gastro/Biliar', 'Cont. Gastro/Biliar'), ('Cisticercose Calcificada', 'Cisticercose Calcificada'), ('Cisticercose Viva', 'Cisticercose Viva'), ('Actinobacilose', 'Actinobacilose')], default='Aprovado', max_length=50),
        ),
        migrations.AlterField(
            model_name='bovino',
            name='pulmoes',
            field=models.CharField(choices=[('Aprovado', 'Aprovado'), ('Aspiração Sangue', 'Aspiração Sangue'), ('Apiração de Vomito', 'Apiração de Vomito'), ('Aderência', 'Aderência'), ('Pleuropneumonia', 'Pleuropneumonia'), ('Abscesso', 'Abscesso'), ('Bronquite', 'Bronquite'), ('Enfisema', 'Enfisema'), ('Hidatidose', 'Hidatidose'), ('Tuberculose(lesão sugestiva)', 'Tuberculose(lesão sugestiva)'), ('Neoplasia', 'Neoplasia'), ('Melanose', 'Melanose')], default='Aprovado', max_length=50),
        ),
        migrations.AlterField(
            model_name='bovino',
            name='rins',
            field=models.CharField(choices=[('Aprovado', 'Aprovado'), ('Cisto Urinário', 'Cisto Urinário'), ('Calculo Renal', 'Calculo Renal'), ('Congestão/Teleangiectasia', 'Congestão/Teleangiectasia'), ('Neoplasia', 'Neoplasia'), ('Hidronefrose/Uronefrose', 'Hidronefrose/Uronefrose'), ('Nefrite', 'Nefrite')], default='Aprovado', max_length=50),
        ),
        migrations.AlterField(
            model_name='bovino',
            name='utero',
            field=models.CharField(choices=[('Aprovado', 'Aprovado'), ('Gestação Adiantada', 'Gestação Adiantada'), ('Metrite', 'Metrite'), ('Abscesso', 'Abscesso'), ('Prenha', 'Prenha')], default='Aprovado', max_length=50),
        ),
    ]
