# Generated by Django 5.2.8 on 2026-03-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frigorifico_app', '0015_avaliacao_obrigatoria_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='bovino',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
